### ISSUE TITLE
Parameter tuning in ntLink_rounds

### ISSUE THREAD

**Issue by SalvadorGJ** [bcgsc/ntLink#86]
Hi,

I open this new issue to solve more doubts about the ntLink parameters. Now I'm testing the **ntLink_rounds**, using the default parameters in the makefile (k=32, w=100), and the process works properly. However, I'm interested in optimize other parameters using the rounds option. While analyzing the makefile, I realized that is not posible to change the parameters **a**, **g** and **f** while calling **ntLink scaffold** inside **ntLink_rounds**, am I right?

I definitively will prefer to increase the threshold for anchored reads **a**, but before tuning the other parameters I need to have a clearer idea about what **g** and **f** mean, and their impact in the workflow.

1. Is it correct to decrease the minimum gap size default value to zero  (g=0)? Why the default is 20?
2. Have you found some advantages in contiguity by increasing the threshold for the transitive pairings list (f=>10)?

Do you recommend to test both cases?

Best,
Salvador

**Comment by lcoombe** [comment]
Hi Salvador,

You are correct - currently the `ntLink_rounds` script is set-up to run iterations of `ntLink` using the same parameters. It uses a liftover approach to avoid re-mapping the reads at each round, which offers considerable time savings (There are more details in our recent Protocol paper: https://doi.org/10.1002/cpz1.733).
If you're looking at changing parameters between iterations, you'd just have to launch the jobs in the more naive way (ie. using a bash script to launch the iterations manually with the desired parameters).

1. The default minimum gap size is just a setting that we've found to work well with various downstream analysis tools. You could lower it, but I'd be hesitant to take it all the way to zero. Since we use a minimizer-based approach to estimate the gap size, it is just that - an estimate calculated using the reads that span those joined contigs. Therefore, keeping "N"s in there allows downstream gap-filling to be able to more precisely assess and attempt to properly fill that gap (and without the N's, no gap-filling can occur).

2. I haven't played around with the transitive pairing threshold too much honestly - during development I found that the default setting was a good compromise between graph completeness and computational efficiency. I wouldn't expect it to have a very big impact on assemblies with decent or moderate contiguity, since it would be relatively unlikely in that case that a single read spanned more than 10 contigs. And even if that was the case, I'm not sure that the extra redundancy introduced by a higher `f` value would have a large impact on the scaffold layout in most cases. But, if you do end up playing around with it, I'd be interested to hear what you find!

Hope that helps!
Lauren

**Comment by SalvadorGJ** [comment]
Thank you so much for your help!

Salvador

**Comment by SalvadorGJ** [comment]
Hi, 

I am reopening this issue because I want to ask for your orientation about the results of a grid parameter search using multiple rounds (3). But before a bit of context. I'm working with a very fragmented draft assembly of a huge genome (>26 Gb), and Nanopore long-reads with an average quality (Q > 7, length > 1kbp). I performed a grid search tuning parameters ***k*** (24,32,40) and ***w*** (100,250,500). The rest of the parameters were kept untouched, including the sensitivity mode off. Also, gap-filling process was made between each round.

First, I show you a pair of plots, the former illustrates the number of contigs and the latter the assembly size (zooming on Y axis!).  

![NContigs_a1](https://user-images.githubusercontent.com/60953895/235966845-b0b28606-2308-41e2-a2e4-a23ea5acd3c1.png)
![GenomeSize_a1](https://user-images.githubusercontent.com/60953895/235966800-15b8c388-8048-4d8d-8340-335aaef508a4.png)

Now, this second results set was generated using the same workflow as before, except that I increased ***a=3***. As expected, the output assemblies were less contiguous than the previous assembly. It's important to note also that the rounds strategy seems to lost its effectiveness by increasing the minimum anchoring reads threshold, very likely because evidence leveraged may be exhausted. In your experience, do you think that an ***a>1*** is too restrictive for the minimizers strategy? I guess that depends greatly on reads' coverage (mine is supposed to be ~13x), but I'm curious about any concerns of keeping the minimum threshold as default (for example false positives). 

![NContigs_a3](https://user-images.githubusercontent.com/60953895/235966872-97dafe64-6ae6-4744-bab1-dbeb3e977592.png)
![GenomeSize_a3](https://user-images.githubusercontent.com/60953895/235966894-36985716-7a94-4e23-9b45-d6ca4758ab24.png)

By other side, it is clear that for my dataset and in both tests ***w*** parameter tuning has more impact than ***k***. But as I barely understand the minimizers alignment, decreasing window size should improve sensitivity, because a larger window will make it harder to distinguish the true smallest minimizer from the noise. Is this assumption correct? Do you know if there is a direct clear relationship between window size and sensitivity?.

Finally, as you stated on the protocol "a smaller k value may be needed to increase the sensitivity of the long-read mapping", but I also noticed that comparing cases where only ***k*** varies, the contiguity is always better using longer kmer size and that genome size very often is increased also by increasing ***k***. I could imagine that longer minimizers may increase sensitivity because are less likely to occur by chance, and shorter minimizers will decrease sensitivity because they will be more prone to errors and false positives. Again, I ask your help to clarify if my ideas are right or plausible, and if in general I should be worried or not about these grid search results.

My next step will be filter input reads by Q>20 and length > 20kbp, looking to enhance the quality at the expense of losing data. Given the current results, do you think that short, low-quality reads could be making a lot of noise during the processes?

Thank you very much for taking the time to read it, also any workflow recommendations or issues you note are welcome!

Best,
Salvador

**Comment by lcoombe** [comment]
Hi @SalvadorGJ,

It's great to see your results!

About the `a` parameter - personally, I always leave it as default, and have not really found any issues. If your coverage is ~13x, I would also worry that a higher `a` could be a bit restrictive, depending on your expected error rate. 

That's interesting to see that `w` matters more than `k` in your case. Do you see a similar trend with the NG50 metric? `w` tuning works in a couple of ways in my experience. Yes, you are right that a lower value should increase specificity, but in practice I also find that too low increases the complexity of the scaffold graph, which can also negatively impact contiguity. So, often there is a sweet spot to find there.

For `k`, yes, especially if you are working with more erroneous reads, lowering the value will increase the sensitivity of the mappings. Increasing `k` will increase the specificity of your mappings because, as you note, you are looking for more specific/unique minimizers. Correspondingly, decreasing `k` decreases the specificity. So, `k` can be a balance between specificity and sensitivity in that way, which is why I recommend parameter sweeps, as there are lots of factors in play including the dataset error rate, repetitiveness of the underlying genome, etc. 

For the filtering, I think that would be an interesting try, but I'd ensure that this filtering doesn't decrease your read coverage too much, since you already only have ~13X, which is already a bit low. It's possible that some lower quality reads could lead to erroneous mappings, but the requirement for at least one 'anchoring read' helps to alleviate that issue. I wouldn't expect shorter, but decent quality reads, to negatively impact the scaffolding.

Let me know if you have any further questions!
Lauren

**Comment by SalvadorGJ** [comment]
Hi @lcoombe 

Thank you so much again for your help. These are the stats for the NG50 metric in the experiment using a=1. The trend is still the same, where w has more impact on contiguity. Please let me know what's your opinion about it.

![NG50_a1](https://user-images.githubusercontent.com/60953895/236821664-d90da8c6-1106-458d-98af-438404a12bce.png)

By now I will try to analyze the others output files, hoping if I'm able to superficially screen which contigs are joined . I'll try just filtering by quality, following your recommendation. 

Best,
Salvador

**Comment by lcoombe** [comment]
Hi Salvador,

Interesting! If you are seeing the best contiguity with the higher `w` value, then I think it makes sense to go with the parameter combination that is maximizing your contiguity!

Let me know if you have any questions about the other output files.

Lauren
