### ISSUE TITLE
Overtrimmed contig ?

### ISSUE THREAD

**Issue by odethier-ulb** [bcgsc/ntLink#87]
Hello,

I used ntLink  v1.3.8 (retrieved with conda) with gap_fill, k=32, w=100 and z=1000 on my assembly and
I noticed an increase in BUSCO missing genes. 

When I looked at the original location on my assembly before ntLink, those genes were situated at the extremities of the contigs.
I tried to blastn one of the contig with the assembly after ntLink and I noticed that around 20 kb were missing.

Hence my question, is it possible that ntLink overtrimmed the contigs before merging them ?

**Comment by odethier-ulb** [comment]
Thank you for your answer. I forgot to mention that it happened during a multiple rounds run. 

I looked at the AGV for my contig of interest (**ptg002001l_1**, length=56677) and for round 1, I have:
...
ntLink_278	1	131908	1	W	ptg000355l_1	1	131908	+
ntLink_278	131909	133464	2	P	m64293e_220725_120726/48826939/ccs	6808	8363	-
ntLink_278	133465	190112	3	W	**ptg002001l_1**	1	56648	-
...
With no problem to retrieve my full contig within ntLink_278 with a blastn

For round 2 I have:
...
ntLink_338	1	162638	1	W	**ntLink_278**	1	162638	+
ntLink_338	162639	5595005	2	W	ntLink_3	19341	5451707	+
ntLink_338	5595006	10165155	3	W	ntLink_6	1	4570150	-
...
But this time I can only retrieve 29204 bases of the contig within ntLink_338.

For my downstream analysis, I can deal with a few missing bits but it is more problematic if I get faulty overlaps in the scaffolded assembly, it there a way to know if it is the case here (or a way to say that it is highly improbable) ?

Also, how important is the quality of the reads used for the scaffolding ? In theory, should we expect less issues like mine if we use only high accurate reads like PacBio HiFi instead of ONT or is it dependent on other variables ?  

Regards,

Olivier

**Comment by lcoombe** [comment]
Thanks for the detail, @odethier-ulb.
So, it does look like this was due to the overlap detection code - You can see that a good chunk of `ntLink_273` was trimmed when incorporated into `ntLink_338`. To really understand why it happened (and if anything in the code can be tweaked to avoid it), I'd need to find a similar example on my side to troubleshoot. Unfortunately, it's not entirely unexpected that errors can happen from time to time.
By "faulty overlaps" - do you mean this over-trimming or misjoins? The best thing to do is really (as you're doing) assess the output scaffolds.

Two parameters that I don't actually document in the help page (to keep it more concise), but you could think about tweaking if you're interested are:
```
# Indexlr parameters for overlapping
small_k=15
small_w=5
```
Increasing `small_k` could help to make the overlap code more specific, at the risk of lower sensititivity.


In terms of the read quality for scaffolding, having higher quality reads can help to increase sensitivity of mappings and of course it means that higher quality bases are incorporated into the assembly during gap filling. But, in my tests, I've found that ntLink works well with reads of varying quality, it just requires some parameter tuning to find the right k/w combination.

**Comment by odethier-ulb** [comment]
I should try your recommendations indeed.

By faulty overlaps, I was meaning misjoins. Is there a way to assess when it is the case ?

**Comment by lcoombe** [comment]
Unfortunately, when you don't have a reference, it isn't too straightforward to assess exactly where you may be getting misjoins. Generally, you would have to use orthogonal data (ex. linked reads as we use for Tigmint, genetic map, knowledge of genes co-occurring on the same chromosome, etc) to assess. Some polishers like Pilon can detect and correct local misassemblies, but that can be fairly computationally intensive.

**Comment by odethier-ulb** [comment]
Normally it's planned to obtain Hi-C data, I guess that we can use that to compare scaffolds generated with Hi-C vs those with ntLink for putative misjoins, but it won't be before a few months probably. In the meantime, thank you for your help :)
