### ISSUE TITLE
Gap filling doubt

### ISSUE THREAD

**Issue by SalvadorGJ** [bcgsc/ntLink#89]
Hi,

This is not a bug or issue, I just want to know what could be the reasons why some potentially fillable gaps (ntlink_patch_gaps.py) at the Gap filling stage were not patched. Knowing this will help me to communicate the results we generated using this tool. Here is an example of the Gap filling summary in the log file:

```
/Apps/ntLink/bin/ntlink_patch_gaps.py --path Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.trimmed_scafs.
path \
 --mappings Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.verbose_mapping.tsv -s Amex6.0-purgedClipped_co
ntigs.ntLink_round1_k56_w1000_a1.correct.fa --reads merged_filtered_reads.Nanopore_R9_and_R10_reads_Q10+_20kbp+.fastq.gz -o Amex6.0-purgedClipp
ed_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.ntLink.scaffolds.gap_fill.fa --large_k 56 --min_gap 1 \
 --trims Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.trimmed_scafs.tsv -k 20 -w 10 
Running ntLink gap-filling...

Parameters:
        --path Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.trimmed_scafs.path
        --mappings Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.verbose_mapping.tsv
        --trims Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.trimmed_scafs.tsv
        -s Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa
        --reads ['merged_filtered_reads.Nanopore_R9_and_R10_reads_Q10+_20kbp+.fastq.gz']

        -z 1000
        -k 20
        -w 10
        -t 4
        --large_k 56
        -x 0
        --min_gap 1
        -o Amex6.0-purgedClipped_contigs.ntLink_round1_k56_w1000_a1.correct.fa.k56.w1000.z1000.ntLink.scaffolds.gap_fill.fa

2023-08-10 17:09:46.094885 Reading ntLink read mappings..
2023-08-10 17:11:56.732905 Reading scaffolds..
2023-08-10 17:13:40.996382 Reading trim coordinates..
2023-08-10 17:13:41.050797 Choosing best read..
2023-08-10 17:13:41.675330 Collecting reads...
2023-08-10 18:01:37.236087 Finding masking points..
2023-08-10 18:01:37.507368 Printing masked sequences..
2023-08-10 18:02:00.384122 Mapping long reads..
2023-08-10 18:03:58.144884 Printing output scaffolds..

Gap filling summary:
Number of detected sequence joins       14863
Number of overlap sequence joins        2235
Number of gaps smaller than threshold   0
Number of potentially fillable gaps     12628
Number of filled gaps   12429
Number of pass 2 anchors used   4786
Number of pass 1 anchors used   7643
```

Finally, I have some assemblies that I generated a time ago, each with their corresponding `.agp file` (after gap-filling), `.dot file`, and `.path` file. Unfortunately, I lack the log file of them, is there a way to recalculate the number of not fillable gaps, by parsing some of the indicated files?

Thanks in advance,
Salvador

**Comment by lcoombe** [comment]
Hello @SalvadorGJ,

Thanks for reaching out!

There is a basic schematic which shows how gap-filling works in this poster presentation: http://www.birollab.ca/assets/posts/CoombeLauren_HitSeq_ISMB2022_goldrush-link.pdf. The gap may not be filled if no 'valid' read is found to fill the gap. That is, there are some checks that we do in the code to find a confident read choice (some more rigorous than we do in the pairing stage), so it's possible in a small number of cases that we thus do not fill a gap.

For retrospectively looking at the gap-filling numbers, you could compare the `trimmed_scafs.agp` and `gap_fill.fa.agp` files. For example, looking at the first few lines of each of these files:
```
(btl) [lcoombe@hpce705 rerun]$ head -n3 celegans_shasta-racon.cut250.tigmint.fa.k24.w250.z1000.trimmed_scafs.agp
ntLink_0	1	387888	1	W	226::226:0-387888	1	387888	+
ntLink_0	387889	387908	2	N	20	scaffold	yes	paired-ends
ntLink_0	387909	395688	3	W	600::600:0-8037	258	8037	-
(btl) [lcoombe@hpce705 rerun]$ head -n3 celegans_shasta-racon.cut250.tigmint.fa.k24.w250.z1000.ntLink.scaffolds.gap_fill.fa.agp 
ntLink_0	1	386210	1	W	226::226:0-387888	1	386210	+
ntLink_0	386211	389230	2	P	7f3f266b-4274-42da-a332-95fe91f16e4c_Basecall_1D_template	2483	5502	-
ntLink_0	389231	392788	3	W	600::600:0-8037	258	3815	-
```
There, you can see the first file has the scaffold gap, and in the second file, that gap was filled in with the noted read (with the noted coordinates).

Lastly, for large gap size estimates, these are estimated based on the reads that support that join. Thus, large gap estimates are possible due to the use of long reads, which give evidence in this scale.

Thank you for your interest in ntLink!
Lauren

**Comment by SalvadorGJ** [comment]
Hello @lcoombe 

Thank you for sharing that useful information. Our main goal is to use the output assembly of ntLink as input of for Hi-C scaffolding tools. Taking into account these un-filled gaps, would you suggest to split the contigs that contain gaps?  I'm worried about how much we can trust in the contig linking where it wasn't possible to fill the gap between them. Also, could you please describe a little more in detail about the checks to find a confident read choice for gap-filling, that will be appreciated. 

Best,
Salvador

**Comment by lcoombe** [comment]
Hi Salvador,

The most relevant check for a 'confident' read choice is that the mapped minimizer positions on the contig are checked for monotonic increasing or decreasing. If all the positions do not satisfy this requirement, then the read will not be considered for gap-filling. So, in a small number of gaps, this could then mean that none of the spanning reads pass the requirement.

Since this is a heuristic, it doesn't mean that the read isn't good evidence that the contigs should be joined, but we opted to be more conservative for gap-filling. In practice, I found that using this check for the pairing stage of ntLink was detrimental to the output scaffolds, but it was beneficial for gap-filling.

In terms of whether you should split these reads - we haven't done this in the past, but if you are very concerned about these joins and want to be extra conservative, you could consider it. I would expect this to break good joins as well as erroneous ones (I looked at a small example on my end for gaps that were not filled, and 2/3 of the cases I looked at were still good joins based on alignments, but I expect that to vary between runs).

Lauren
