### ISSUE TITLE
Scaffolds trimmed before gapfiling or misassembled?

### ISSUE THREAD

**Issue by nam-hoang** [bcgsc/ntLink#90]
Hi Lauren @lcoombe and Ntlink users,

I would be highly appreciated if you could share your thoughts on this?
I used NtLink gapfiling to scaffold my draft genome assembly using Nanopore data and then polish the resulting assembly using both Nanopore and Illumina data. Overall, the results look great, and I got a higher N50 and an improved BUSCO, and also slightly better mapping rate.

However, when I took one of the longest scaffolds to analyze the alignment of the initial scaffolds and supporting Nanopore reads onto this final scaffold, it looks to me that there are some parts of the scaffolds are not really well-mapped. Please see a snapshot below. The dark green indicates high homology, while the light green indicates a low homology (very poorly aligned when I zoomed in). Some parts of the original scaffolds (4-9) did not align well to the final scaffold (red dash boxes). These supporting reads and scaffolds were listed in the APG file and were mapped to the final scaffold (ntLink_0, 22 Mb) using Minimap2.  

I wonder if this is due to those parts being trimmed and replaced by Nanopore read data (for example, due to misassemblies in our initial draft scaffolds), or the identification of Nanopore reads for these gaps were not correct? I can seem to find any Nanopore reads that actually span through these regions in the AGP though. What would be the best way to validate this?

Thank you very much, and I am looking forward to hearing from you.
Best regards,
Nam

![image](https://github.com/bcgsc/ntLink/assets/90763225/1d8563da-8677-403b-8302-921406591031)

**Comment by lcoombe** [comment]
Hello Nam,

Glad to hear that the results look great overall!

Yes, when you use gap-filling the flanking scaffolds can be trimmed as a result. That is due to how the gap-filling works - essentially after choosing a read to fill the gap, it will look for minimizer anchors between the read and the flanks. Sometimes, that anchor is a certain distance from the end of the scaffold, hence the trimming. There's more info about the gap-filling approach in our protocol paper and a conference poster if you're interested: 
https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpz1.733
http://www.birollab.ca/assets/posts/CoombeLauren_HitSeq_ISMB2022_goldrush-link.pdf

In terms of validation, if you wanted to, you could look through the 'verbose mapping file' - this has the long read mappings that ntLink uses to both make the joins and to fill in gaps. There's info about the file format here: https://github.com/bcgsc/ntLink/wiki/Output-file-formats

I hope that makes sense - thank you for your interest in ntLink!
Lauren

**Comment by nam-hoang** [comment]
Thank you very much Lauren @lcoombe for your suggestion and information. I could see a lot of reads now in the verbose_mapping_file, and also in the mapping file. Because I initially trimmed my Nanopore data with a minimum length of 1000 bp, now, I am doing mapping again with longer reads (min 10 kb) to analyze it easier.

In the APG file, there are just a few reads supported the gaps (1 or 2 per gap, in my case, read names Ont_read shown in the figure above). I wonder if these are all evidence that I have or there are more but these are just a few that were selected and reported in the APG file?

Thank you very much.
Nam

**Comment by lcoombe** [comment]
Hi Nam,

The gap-fill AGP file only shows the output composition of the scaffolds, so it doesn't give you the information about how many reads support a given join. For example:
```
ntLink_0        1       33470   1       W       188266  1       33470   +
ntLink_0        33471   39162   2       P       42601c42-926c-46c1-a103-f84988cb196e_Basecall_1D_template       6398    12089   +
ntLink_0        39163   87420   3       W       189231  1       48258   -
``` 
Here - we see two contigs joined together with the one ONT read (middle line) used with the shown coordinates to fill the gap. But, if I look into the graph file, I could see that many more reads (11 in my test example) support that join.

**Comment by nam-hoang** [comment]
Oh, I see! Thank you very much for your clear explanation @lcoombe ! I really appreciate it! ;D

**Comment by lcoombe** [comment]
No worries! Let me know if you have any more questions!
