### ISSUE TITLE
Question about read chimeras

### ISSUE THREAD

**Issue by mylena-s** [bcgsc/ntLink#96]
Hello! 
Thank you for developing this tool, it runs smoothly and is super easy to install and run.

I am scaffolding with UL nanopore reads, and I was wondering on the impact of read chimeras in the final scaffolds. How does ntLink deal with this? 
Should I remove read chimeras before running ntLink? does increasing the value of the parameter a help me avoid mis-scaffolding due to chimeras? 

Thank you in advance!
Cheers
M

**Comment by lcoombe** [comment]
Hi @mylena-s,

For the most part, I'd expect the impact of read chimeras to be minimized by the approaches used to filter the scaffold graph and the redundancy in the read set. 
For example, say you have scaffolds A and B that should be joined together, but a chimeric read that makes an edge between A and another scaffold X. We don't expect the chimeric read to have redundancy (ie. many chimeric reads supporting that join), so that's just one read that is making a noisy edge, but many other reads that would support A-B. In the graph filtering and traversal, the correct path would be much better supported by the reads (higher edge weight in the scaffold graph), so the correct join should be made.
Of course, there would be edge cases, but for the most part, I'd expect the above logic to hold.

But, if you want to be more stringent about the scaffolding (which would also result in less contiguous scaffolds), then yes, the `a` parameter could be increased, even just to 2.

I hope that helps - thank you for your interest in ntLink!
Lauren

**Comment by mylena-s** [comment]
Thank you Lauren for the help!
The information was super clear! Thanks

Mylena
